version: '3.8'

services:
  # 1. Developer Environment
  dev-app:
    build:
      context: .
      target: dockerfile
    container_name: tailwind-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

 
